### ISSUE TITLE
Pico 4 Support

### ISSUE THREAD

**Issue by Myrothas** [tommaier123/NoodleManagerX#18]
Seems to not work yet.

**Comment by tommaier123** [comment]
I don't have a pico so I can't test it.
Does the pico show up in windows when you connect it?
As long as that happens and there is a SynthRidersUC folder in the top directory it should work.

**Comment by Myrothas** [comment]
I will test it in aprox 5 hours from now again and keep you updated on my findings.

**Comment by Myrothas** [comment]
Alright, seems to work now without any issues. The Folders were not created yet. Thanks for trying to help tho. Love the tool!
