### ISSUE TITLE
Warning on exit about mystery downloads in progress

### ISSUE THREAD

**Issue by YoukaiTheGit** [tommaier123/NoodleManagerX#2]
Steps:
1. Installed & Ran v0.5.0 NoodleManagerX for the first time
2. Used 'Get all' button to download all songs.  It appeared to download just about everything, including deleting older songs & redownloading them.  The download progress bar/line filled up & then cleared.
3. Later, tried to exit the app with the 'X' button, and got this warning about 3 downloads in progress: ![image](https://user-images.githubusercontent.com/75144814/152702532-9e8253b6-6fed-4f1f-92cc-9f0e9c12e89e.png)

There's no other indication that downloads are still in progress, or a way to know what they might be.

**Comment by YoukaiTheGit** [comment]
Logfile attached
[Log.txt](https://github.com/tommaier123/NoodleManagerX/files/8011305/Log.txt)

**Comment by tommaier123** [comment]
There are two things going on here. 
It shouldn't have redownloaded everything. Seems like it though all the maps were corrupted.
I'll keep this in mind but while adding quest support the whole way the storage is accessed was changed so the bug might be fixed already.
The other thing is when the progress-bar shows completed, up to four songs can still be downloading. I'll fix this by updating the progress-bar not when a download is started but when it completes.

**Comment by YoukaiTheGit** [comment]
> when the progress-bar shows completed, up to four songs can still be downloading

At the time I got the download warning on exit, it had been at least 10 minutes since the progress bar had cleared.

**Comment by tommaier123** [comment]
There is probably some failure that doesn't remove the songs from the queue. I'll have to add more logging to be sure what happened.

**Comment by tommaier123** [comment]
I think I have found the problem. I saw some server errors in your log and there was a bug where maps were requeued twice when that happens.

**Comment by tommaier123** [comment]
Fixed in full release
