### ISSUE TITLE
Set download directory

### ISSUE THREAD

**Issue by Localhorst86** [tommaier123/NoodleManagerX#3]
How can you set the download diretory manually? I do not have synthriders installed on my PC and would like to have noodlemanagerX to download the songs to a specified directory (located on a NAS) so I can then copy the files via WiFi on my Quest 2.

When I try to set the path to my Synthriders folder on my network drive, NMX does not accept it - because it only contains the "CustomStages" and "CustomSongs" directories.
![grafik](https://user-images.githubusercontent.com/30772376/154568095-d18eb9c4-73e6-462e-9933-0fce32dcc69b.png)

**Comment by tommaier123** [comment]
It looks for the SynthRiders.exe, so if you add that to the directory that contains the CustomSongs folder it should work.
I am planning on adding a proper way to do this, just haven't decided how. Maybe I'll add a button to override the directory validation.

**Comment by Localhorst86** [comment]
Alright, added a blank text file renamed to synthriders.exe to the folder. Looks like that'll work for me

**Comment by tommaier123** [comment]
The next version has a settings option to disable the directory check. So you won't need the SynthRiders.exe anymore.
