### ISSUE TITLE
Progress bar for downloads?

### ISSUE THREAD

**Issue by FolkSong** [tommaier123/NoodleManagerX#4]
I see this listed in the release notes but I don't see anything like that in the app. In fact nothing appears to happen when I click download, making me wonder if I even clicked it, but after a short delay the listing turns grey to show that it's done.

I'm using a Quest.

**Comment by tommaier123** [comment]
The progressbar shows up when downloading multiple songs. It indicates how many songs from the download queue are done. Because downloading a single song is very quick there is non additional progress indication.

**Comment by tommaier123** [comment]
The download button now turns grey when a song is being downloaded
