### ISSUE TITLE
Filter installed songs

### ISSUE THREAD

**Issue by MichaelBelgium** [tommaier123/NoodleManagerX#5]
In the previous noodlemanager you could see a list of all your downloaded/installed custom songs, now there's not?

**Comment by tommaier123** [comment]
The downloaded songs have grey text, the undownloaded have white text. So you can see which songs are downloaded. Showing all downloaded songs is not possible because of the pagination. But it also wasn't possible with the old NM because it only showed the latest 100 maps.
