### ISSUE TITLE
No MTP Device found

### ISSUE THREAD

**Issue by Breltron** [tommaier123/NoodleManagerX#6]
In trying to connect my quest via cable to my PC I don't get the pop up to allow access to data. I then click on the PC button in noodle manager I receive a message saying "No MPT device found. Make sure to allow storage access on the head set." I could not find a way to allow storage on my headset.

**Comment by tommaier123** [comment]
Have you tried the steps in [FAQ](https://github.com/tommaier123/NoodleManagerX/wiki/3%29-FAQ)?
